baseURL = "/"
canonifyURLs = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
languageCode = "en-US"
theme = "hugo-theme-learn"
themesdir = "themes"
title = "SAP on Azure - Tutorials and Guides"
[Languages.en]
landingPageName = "<i class='fas fa-home'></i> Home"
landingPageURL = "/"
languageName = "English"
title = "SAP on Microsoft - Tutorials"
weight = 1
[[Languages.en.menu.shortcuts]]
identifier = "ds"
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
url = "https://github.com/abicas/SapOnMicrosoftDemos"
weight = 10
[[Languages.en.menu.shortcuts]]
identifier = "hugodoc"
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
url = "https://gohugo.io/"
weight = 20
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
alwaysopen = false
author = "Alexandre Bicas"
collapsibleMenu = true
customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
description = "SAP on Microsoft - Tutorials"
disableBreadcrumb = false
disableLandingPageButton = false
disableMermaid = false
disableNextPrev = false
showVisitedLinks = true
titleSeparator = "::"
